version: '3.4'

services:
  blazorproject.server:
       container_name: App
       image: catalinbuza31/blazorprojectserver:latest
       ports:
          - "8080:80"
       environment:
          - ConnectionStrings__DefaulConnection=User ID=postgres;Password=postgres;Server=db;Host=db;Port=5432;Database=postgres;Integrated Security=true;Pooling=true

       depends_on:
              - db
  db:
       container_name: db
       image: postgres:latest
       restart: always
       environment:
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_DB=postgres
       ports:
         - "5432:5432"
       volumes:
         - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
   
